language: scala
matrix:
  include:
    - scala: 2.11.12
      jdk: openjdk8
    - scala: 2.12.10
      jdk: openjdk8
    - scala: 2.12.10
      jdk: oraclejdk11
    - scala: 2.13.0
      jdk: openjdk8
    - scala: 2.13.0
      jdk: oraclejdk11
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
script:
  - sbt compileNative
  - sbt +test
